spring.application.name=AutoLink-bn

server.port=${SERVER_PORT}

#DB
spring.data.mongodb.uri=${MONGO_DB_URL}

#cors
spring.allowed-origin=${ALLOWED_ORIGIN}
frontend.allowed-origin=${FRONTEND_ALLOW_ORIGIN}

#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#jwt
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.reset-password-secret=${JWT_RESET_SECRET}


#firebase
firebase.server.key=BOtP5Sc2tGaw2-UhUmHIYXAuN3Gz65B1Uw2kNAAr3gXcBZ8pkw3l-00kgLIpvLxdtPpa6z_Mpl2WIDCO4MExUg4